spring:
  application:
    name: temp-test
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import: nacos:services-products.yml
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8090