spring:
  cloud:
    gateway:
      routes:
        - id: order-route  #路由规则id，自定义，唯一
          uri: lb://services-order  #路由目标微服务，lb代表负载均衡
          predicates:  #路由断言，判断请求是否符合规则，符合则路由到目标
            - Path=/api/order/**  #以请求路径做判断
        - id: products-route
          uri: lb://services-products
          predicates:
            - Path=/api/products/**
      #全局跨域设置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
#id表示路由的名字
#uri表示把请求转到哪
#predicates表示路由的匹配规则
#-Path表示路径为api/order/开头的都转给uri