spring:
  application:
    name: services-transactional
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: f5bf2bca-408f-4ddc-82c3-59a702ca8607
        group: SEATA_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: f5bf2bca-408f-4ddc-82c3-59a702ca8607
        group: SEATA_GROUP
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata?useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123123
logging:
  level:
    com.alibaba.nacos: DEBUG
server:
  port: 7001
seata:
  tx-service-group: g1
  registry:
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: f5bf2bca-408f-4ddc-82c3-59a702ca8607
      group: SEATA_GROUP
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: f5bf2bca-408f-4ddc-82c3-59a702ca8607
      username: nacos
      password: nacos
      data-id: seataServer.properties