spring:
  application:
    name: services-products
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  profiles:
    include: feign
logging:
  level:
    org.springframework.cloud.openfeign: debug
#server:
#  port: 8081

